import type { IconType } from "react-icons";
import { AiFillGithub, AiOutlineTwitter } from "react-icons/ai";
import {
  DiBootstrap,
  DiCss3,
  DiGit,
  DiHtml5,
  DiJavascript1,
  DiMongodb,
  DiNodejs,
  DiPython,
  DiReact,
  DiVisualstudio,
} from "react-icons/di";
import { FaAws, FaBrain, FaChrome, FaCogs, FaFacebook, FaLinkedinIn, FaRobot } from "react-icons/fa";
import {
  SiExpress,
  SiFirebase,
  SiGithub,
  SiGoogle,
  SiGitlab,
  SiHeroku,
  SiJira,
  SiMui,
  SiMysql,
  SiNextdotjs,
  SiOpenai,
  SiPostgresql,
  SiPostman,
  SiRedux,
  SiSentry,
  SiTailwindcss,
  SiTrello,
  SiTypescript,
  SiVercel,
  SiVite,
  SiWebpack,
} from "react-icons/si";

const iconMap: Record<string, IconType> = {
  AiFillGithub,
  AiOutlineTwitter,
  DiBootstrap,
  DiCss3,
  DiGit,
  DiHtml5,
  DiJavascript1,
  DiMongodb,
  DiNodejs,
  DiPython,
  DiReact,
  DiVisualstudio,
  FaAws,
  FaBrain,
  FaChrome,
  FaCogs,
  FaFacebook,
  FaLinkedinIn,
  FaRobot,
  SiExpress,
  SiFirebase,
  SiGithub,
  SiGoogle,
  SiGitlab,
  SiHeroku,
  SiJira,
  SiMui,
  SiMysql,
  SiNextdotjs,
  SiOpenai,
  SiPostgresql,
  SiPostman,
  SiRedux,
  SiSentry,
  SiTailwindcss,
  SiTrello,
  SiTypescript,
  SiVercel,
  SiVite,
  SiWebpack,
};

export function getIconComponent(iconName: string): IconType | null {
  return iconMap[iconName] ?? null;
}
